package com.example.login.com.example;
import UserDao.UserDAO;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.stage.Stage;
import model.User; // Assuming User model is in model package

import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;

public class AuthController {

    @FXML
    private TextField nom;

    @FXML
    private TextField prenom;

    @FXML
    private TextField mail;

    @FXML
    private PasswordField passwd;

    @FXML
    private PasswordField confirmPasswd;

    @FXML
    private TextField telephone;

    @FXML
    private TextField pays;

    @FXML
    private ComboBox<String> genre;

    @FXML
    private DatePicker dateNaissance;

    @FXML
    private TextField besamee;

    @FXML
    private CheckBox termsCheckBox;

    @FXML
    private Button btnCreateAccount;

    @FXML
    private Label errorLabel;

    private UserDAO userDAO;

    public AuthController() {
        this.userDAO = new UserDAO();
    }

    @FXML
    public void initialize() {
        // Populate ComboBox with gender options
        genre.getItems().addAll("Masculin", "Féminin", "Autre");
    }

    @FXML
    public void onCreateAccount() {
        errorLabel.setText(""); // Clear previous error messages

        // Validate inputs
        String nomText = nom.getText().trim();
        String prenomText = prenom.getText().trim();
        String emailText = mail.getText().trim();
        String passwordText = passwd.getText();
        String confirmPasswordText = confirmPasswd.getText();
        String telephoneText = telephone.getText().trim();
        String paysText = pays.getText().trim();
        String genreText = genre.getValue();
        LocalDate dateNaissanceValue = dateNaissance.getValue();
        String besameeText = besamee.getText().trim();

        if (!termsCheckBox.isSelected()) {
            errorLabel.setText("Vous devez accepter les termes et conditions.");
            return;
        }

        if (nomText.isEmpty() || prenomText.isEmpty() || emailText.isEmpty() || passwordText.isEmpty() ||
                telephoneText.isEmpty() || paysText.isEmpty() || genreText == null || dateNaissanceValue == null) {
            errorLabel.setText("Tous les champs obligatoires doivent être remplis.");
            return;
        }

        if (!passwordText.equals(confirmPasswordText)) {
            errorLabel.setText("Les mots de passe ne correspondent pas.");
            return;
        }

        if (!emailText.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            errorLabel.setText("Adresse email invalide.");
            return;
        }

        try {
            if (userDAO.emailExists(emailText)) {
                errorLabel.setText("Cet email est déjà utilisé.");
                return;
            }

            // Create User object
            User newUser = new User(
                    0, // ID will be auto-generated by DB
                    nomText,
                    prenomText,
                    emailText,
                    passwordText, // In production, hash this password
                    telephoneText,
                    paysText,
                    genreText,
                    java.sql.Date.valueOf(dateNaissanceValue),
                    besameeText
            );

            // Save to database
            userDAO.addUser(newUser);

            // Redirect to Acc.fxml
            loadScene("/com/example/demo1/Acc.fxml", "SportConnect - Home");

        } catch (SQLException e) {
            errorLabel.setText("Erreur lors de la création du compte : " + e.getMessage());
            e.printStackTrace();
        } catch (IOException e) {
            errorLabel.setText("Erreur lors du chargement de la page : " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void loadScene(String fxmlPath, String title) throws IOException {
        FXMLLoader loader = new FXMLLoader(getClass().getResource(fxmlPath));
        Parent root = loader.load();

        // If redirecting to Acc.fxml, pass email if needed
        if (fxmlPath.equals("/com/example/demo1/Acc.fxml")) {
            AccController controller = loader.getController();
            controller.setLoggedInEmail(mail.getText().trim());
        }

        Stage stage = (Stage) btnCreateAccount.getScene().getWindow();
        Scene scene = new Scene(root);
        stage.setScene(scene);
        stage.setTitle(title);
        stage.show();
    }
}